### ISSUE TITLE
フラッシュメッセージの実装

### ISSUE THREAD

**Issue by snowhork** [snowhork/protospace#8]
# WHAT
- [x] サインイン成功・失敗時のメッセージ
- [x] サインアップ成功・失敗時のメッセージ
- [x] サインアウト成功時のメッセージ
- [x] ユーザー情報編集時のメッセージ
# WHY

各アクションに対して成功か失敗したかをユーザーに簡潔に表示するため
# deadline

8/7

**Comment by sainu** [comment]
@snowhork マークダウンが当たっていないので、見直してください！

**Comment by sainu** [comment]
@snowhork タスクに関しては、チェックボックスにすると管理しやすいです。

```
- [ ] task1
- [ ] task2
```

**Comment by snowhork** [comment]
@sa-inu できました！

**Comment by sainu** [comment]
@snowhork `why` が `why` になっていないので、変更しましょう

**Comment by sainu** [comment]
@snowhork どうしてフラッシュメッセージを表示する必要があるのか、に対する回答を書きましょう😁

**Comment by snowhork** [comment]
@sa-inu 編集しました！

**Comment by sainu** [comment]
@snowhork  おっけいです！
そしたら、作成するブランチ名は `feature/8_hgoehoge` とかって名前にしてみましょう。これは `git flow` と言う開発方法に基づいています。調べてみてください！
git flowでやるのかgithub flowでやるのか、プロジェクトによって始めに決定しておくべきですが、今回は経験のためいろんな開発方法を試しながらやっていきます！

**Comment by snowhork** [comment]
@sa-inu プルリク出しました、こんな感じでいいですか？

**Comment by sainu** [comment]
@snowhork 返信遅くなりました、おっけいです👌issueはこのままにしておいてください、これに関連したプルリクがマージされたらこのissueをcloseします。

**Comment by snowhork** [comment]
@sa-inu 実装しました！
